markdown: enhanced_kramdown
pygments: true
lsi: false
safe: false
baseurl: /pulsar

kramdown:
  use_coderay: false

# Site globals used throughout docs.
project: Pulsar
version: 0.7.2
github: puniverse/pulsar
google_group: "https://groups.google.com/forum/#!forum/quasar-pulsar-user"
ga_tracking_id: UA-25007319-2
